Project2/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Project2.Models;
using Project2.Azure_DB;
using System.Net;
using System.Data.Entity;
using OfficeOpenXml;
using OfficeOpenXml.Style;
using System.Data.Entity.Infrastructure;

namespace Project2.Controllers
{
    public class AdminController : Controller
    {
        private readonly CrsInternServcieEntities1 _db;
        private static string internUrl;
        private static string yearUrl;
        private static string monthUrl;
        public AdminController()
        {
            _db = new CrsInternServcieEntities1();
        }
        // GET: Admin
        public ActionResult AdminIndex(string year, string month, string internName)

        {
            //if (AdminAuthentication())
            //{
                AdminViewModel viewModel = new AdminViewModel();
                viewModel.PartialTask = GetTasks();
                viewModel.PartialSignin = GetSignins();


                if (year != null && month != null && internName != null)
                {
                    var monthNum = Convert.ToInt32(month);
                    var yearNum = Convert.ToInt32(year);

                    var userName = _db.Task.Where(x => x.UserName == internName);
                    var taskResult = userName.Where(x => x.Date.Month == monthNum && x.Date.Year == yearNum).OrderBy(x => x.Date).ToList();

                    var userName1 = _db.Signin.Where(x => x.UserName == internName);
                    var signinResult = userName1.Where(x => x.WorkDate.Month == monthNum && x.WorkDate.Year == yearNum).OrderBy(x => x.WorkDate).ToList();

                    viewModel.PartialTask = taskResult;
                    viewModel.PartialSignin = signinResult;

                    internUrl = internName;
                    yearUrl = year;
                    monthUrl = month;

                    HttpCookie cookie = new HttpCookie("filterCookie");
                    cookie.Values.Add("internUrl", internName);
                    cookie.Values.Add("yearUrl", year);
                    cookie.Values.Add("monthUrl", month);
                    Response.Cookies.Add(cookie);

                    return View(viewModel);
                }

                return View(viewModel);
            //}

            //return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        }

        private List<Task> GetTasks()
        {
            List<Task> tasks = new List<Task>();
            return tasks;
        }

        public List<Signin> GetSignins()
        {
            List<Signin> signins = new List<Signin>();
            return signins;
        }

        public FileContentResult DownloadCSV()
        {
            string csv = "Charlie, Chaplin, Chuckles" + Environment.NewLine  + "abc";
            return File(new System.Text.UTF8Encoding().GetBytes(csv), "text/csv", "InternReport.csv");
        }

        // GET: Admin/worklistEdit/5
        public ActionResult WorklistEdit(int? id)
        {
            //if (AdminAuthentication())
            //{
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }

                Task task = _db.Task.Find(id);
                if (task == null)
                {
                    return HttpNotFound();
                }

                return View(task);
            //}

            //return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        }

        // POST: Admin/worklistEdit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult WorklistEdit([Bind(Include = "TaskId, TaskName, Duration")] Task task)
        {
            if (ModelState.IsValid)
            {
                task.UserName = internUrl;
                _db.Entry(task).State = EntityState.Modified;
                _db.SaveChanges();
                return RedirectToAction("AdminIndex", new { year = yearUrl, month = monthUrl, internName = internUrl });
            }
            return View(task);
        }

        // GET: Admin/signinEdit/5
        public ActionResult SigninEdit(int? id)
        {
            //if (AdminAuthentication())
            //{
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }

                Signin signin = _db.Signin.Find(id);

                if (signin == null)
                {
                    return HttpNotFound();
                }
                return View(signin);
            //}
            //return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        }

        // POST: Admin/signinEdit/5
        [HttpPost]
        public ActionResult SigninEdit([Bind(Include = "SigninId, WorkDate, ArrivedTime, LeaveTime, CheckValue")] Signin signin)
        {
            if (ModelState.IsValid)
            {
                signin.UserName = internUrl;
                _db.Entry(signin).State = EntityState.Modified;
                _db.Configuration.ValidateOnSaveEnabled = false;
                _db.SaveChanges();
                return RedirectToAction("AdminIndex", new { year = yearUrl, month = monthUrl, internName = internUrl});
            }
            return View(signin);
        }

        // GET: Admin/worklistDelete/5
        public ActionResult WorklistDelete(int? id)
        {
            //if (AdminAuthentication())
            //{
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }

                Task task = _db.Task.Find(id);
                if (task == null)
                {
                    return HttpNotFound();
                }
                return View(task);
            //}

            //return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        }

        // POST: Admin/worklistDelete/5
        [HttpPost, ActionName("WorklistDelete")]
        [ValidateAntiForgeryToken]
        public ActionResult WorklistDeleteConfirmed(int id)
        {
            Task task = _db.Task.Find(id);
            _db.Task.Remove(task);
            _db.SaveChanges();
            return RedirectToAction("AdminIndex", new { year = yearUrl, month = monthUrl, internName = internUrl });
        }

        // GET: Admin/signinDelete/5
        public ActionResult SigninDelete(int? id)
        {
            if (AdminAuthentication())
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Signin signin = _db.Signin.Find(id);
                if (signin == null)
                {
                    return HttpNotFound();
                }
                return View(signin);
            }
            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        }


        // POST: Admin/singinDelete/5
        [HttpPost, ActionName("SigninDelete")]
        [ValidateAntiForgeryToken]
        public ActionResult SigninDeleteConfirmed(int? id)
        {
            Signin signin = _db.Signin.Find(id);
            _db.Signin.Remove(signin);
            _db.SaveChanges();
            return RedirectToAction("AdminIndex", new { year = yearUrl, month = monthUrl, internName = internUrl });
        }

        public bool AdminAuthentication()
        {
            if (System.Web.HttpContext.Current.User.Identity.Name.Contains("AnYun") || System.Web.HttpContext.Current.User.Identity.Name.Contains("Ryuk"))
            {
                return true;
            }
            return false;
        }

        public void ExportToExcel()
        {
            ExcelPackage pck = new ExcelPackage();
            ExcelWorksheet ws = pck.Workbook.Worksheets.Add("InternReport");
            HttpResponse response = System.Web.HttpContext.Current.Response;

            var internName = HttpUtility.ParseQueryString(Request.UrlReferrer.Query)["internName"];
            var month = HttpUtility.ParseQueryString(Request.UrlReferrer.Query)["month"];
            var year = HttpUtility.ParseQueryString(Request.UrlReferrer.Query)["year"];

            ws.Cells["A1:P1"].Merge = true;
            ws.Cells["A1:I1"].Style.HorizontalAlignment = ExcelHorizontalAlignment.Center;
            ws.Cells["A1:P1"].Value = "雲馥數位科技股份有限公司";
            ws.Cells["A2:I2"].Merge = true;
            ws.Cells["A2:I2"].Value = "簽到表";

            ws.Cells["A3:B3"].Merge = true;
            ws.Cells["C3:I3"].Merge = true;
            ws.Cells["L3:P3"].Merge = true;
            ws.Cells["J3:K3"].Merge = true;
            ws.Cells["A3:B3"].Value = "實習生";
            ws.Cells["C3"].Value = internName;
            ws.Cells["C3:D3"].Value = System.Web.HttpContext.Current.User.Identity.Name;
            ws.Cells["J3:K3"].Value = "指導人";

            ws.Cells["A4:P4"].Merge = true;

            //set all cells text-center
            ws.Cells[1, 1, 39, 16].Style.HorizontalAlignment = ExcelHorizontalAlignment.Center;
            ws.Cells[1, 1, 39, 16].Style.Font.Name = "微軟正黑體";

            //prepare excel column
            ws.Cells["A5:B5"].Value = "日期";
            ws.Cells["A5:B5"].Merge = true;
            ws.Cells["A5:B5"].Style.Font.Bold = true;
            ws.Cells["C5:D5"].Merge = true;
            ws.Cells["C5:D5"].Value = "上班簽到時間";
            ws.Cells["C5:D5"].Style.Font.Bold = true;
            ws.Cells["E5:F5"].Merge = true;
            ws.Cells["E5:F5"].Value = "下班簽到時間";
            ws.Cells["E5:F5"].Style.Font.Bold = true;
            ws.Cells["G5"].Value = "確認人";
            ws.Cells["G5"].Style.Font.Bold = true;
            ws.Cells["H5:I5"].Merge = true;
            ws.Cells["H5:I5"].Value = "總計";
            ws.Cells["H5:I5"].Style.Font.Bold = true;
            ws.Cells["G37"].Style.Font.Bold = true;
            ws.Cells["H37:I37"].Merge = true;

Project2/Controllers/SigninController.cs
using System;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using Project2.Azure_DB;

namespace Project2.Controllers
{
    public class SigninController : Controller
    {
        private readonly CrsInternServcieEntities1 _db;

        public SigninController()
        {
            _db = new CrsInternServcieEntities1();
        }

        // GET: Signin
        public ActionResult Index(string year, string month)
        {
            if (System.Web.HttpContext.Current.User.Identity.Name != null)
            {
                string un = System.Web.HttpContext.Current.User.Identity.Name;
                var result = _db.Signin.Where(x => x.UserName == un).OrderBy(x => x.WorkDate);

                if (month != null)
                {
                    var lastMonth = Convert.ToInt32(month) - 1;
                    var nextYear = 0;
                    if (month == "12")
                    {
                        nextYear =+ 1;
                    }
                    else
                    {
                        nextYear = Convert.ToInt32(year);
                    }
                    DateTime endDate = new DateTime(nextYear, Convert.ToInt32(month), 20, 23, 59, 59);
                    DateTime startDate = new DateTime(Convert.ToInt32(year), lastMonth, 21, 0, 0, 0);
                    var yearNum = Convert.ToInt32(year);
                    var monthNum = Convert.ToInt32(month);
                    var userName = _db.Signin.Where(x => x.UserName == un);
                    var result1 = userName.Where(x => x.WorkDate.CompareTo(startDate) >= 0 && x.WorkDate.CompareTo(endDate) < 0).OrderBy(x => x.WorkDate).ToList();
                    return View(result1);
                }
                return View(result);
            }

                return HttpNotFound();
        }

        // GET: Signin/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Signin/Create
        [HttpPost]
        public ActionResult Create([Bind(Include = "SigninId, WorkDate, ArrivedTime, LeaveTime, UserName")] Signin signin)
        {
            if (ModelState.IsValid)
            {
                signin.UserName = System.Web.HttpContext.Current.User.Identity.Name;
                _db.Signin.Add(signin);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(signin);
        }

        // GET: Signin/Delete/5
        public ActionResult Delete(int? id)
        {
            if (SigninAuthentication(id))
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Signin signin = _db.Signin.Find(id);
                if (signin == null)
                {
                    return HttpNotFound();
                }
                return View(signin);
            }
            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        }
        

        // POST: Signin/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int? id)
        {
            Signin signin = _db.Signin.Find(id);
            _db.Signin.Remove(signin);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        // GET: Signin/Edit/5
        public ActionResult Edit(int? id)
        {
            if (SigninAuthentication(id))
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Signin signin = _db.Signin.Find(id);
                if (signin == null)
                {
                    return HttpNotFound();
                }
                return View(signin);
            }
            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        }

        // POST: Signin/Edit/5
        [HttpPost]
        public ActionResult Edit([Bind(Include = "SigninId, WorkDate, ArrivedTime, LeaveTime")] Signin signin)
        {
            if (ModelState.IsValid)
            {                
                _db.Entry(signin).State = EntityState.Modified;
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(signin);
        }

        public bool SigninAuthentication(int? id)
        {
            var name = _db.Signin.Where(x => x.SigninId == id).Select(x => x.UserName).SingleOrDefault().ToString();
            if (name == System.Web.HttpContext.Current.User.Identity.Name)
            {
                return true;
            }
            else
            {
                return false;
            }
        }

    }
}

Project2/Views/Admin/AdminIndex.cshtml
@model Project2.Models.AdminViewModel
@{
    ViewBag.Title = "AdminIndex";
}


    <div id="result">
        <h2>實習時數檢視</h2>

        <table class="table  table-hover card-text">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.PartialTask.First().TaskName)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.PartialTask.First().Duration)
                    </th>
                    <th class="col-lg-3">
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.PartialTask)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.TaskName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Duration)
                        </td>
                        <td class="col-lg-2">
                            <a href="@Url.Action("WorklistEdit", new { id = item.TaskId })">
                                <img src="https://crsinternserviceimage.blob.core.windows.net/crsinternserviceimage/edit_btn.png" style="width:60px" />
                            </a>
                            <a href="@Url.Action("WorklistDelete", new { id = item.TaskId })">
                                <img src="https://crsinternserviceimage.blob.core.windows.net/crsinternserviceimage/delete_btn.png" style="width:80px" />
                            </a>
                        </td>
                    </tr>
                }
                <tr>
                    <td></td>
                    <td><u>@Model.PartialTask.Sum(b => b.Duration)</u></td>
                    <td></td>
                </tr>
            </tbody>
        </table>

        <table class="table  table-hover card-text">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.PartialSignin.First().WorkDate)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.PartialSignin.First().ArrivedTime)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.PartialSignin.First().LeaveTime)
                    </th>
                    <th>總時間</th>
                    <th>
                        @Html.DisplayNameFor(model => model.PartialSignin.First().CheckValue)
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.PartialSignin)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.WorkDate)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.ArrivedTime)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.LeaveTime)
                        </td>
                        <td>
                            @{
                                var a = item.ArrivedTime.Hours;
                                var b = item.LeaveTime.Hours;
                                var workTime = b - a - 1;
                            }
                            @(workTime)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.CheckValue)
                        </td>
                        <td class="col-lg-2">
                            <a href="@Url.Action("SigninEdit", new { id = item.SigninId })">
                                <img src="https://crsinternserviceimage.blob.core.windows.net/crsinternserviceimage/edit_btn.png" style="width:60px" />
                            </a>
                            <a href="@Url.Action("SigninDelete", new { id = item.SigninId })">
                                <img src="https://crsinternserviceimage.blob.core.windows.net/crsinternserviceimage/delete_btn.png" style="width:80px" />
                            </a>
                        </td>
                    </tr>
                }
                <tr>
                    <td></td>
                    <td></td>
                    <td></td>
                    @{ double time = Model.PartialSignin.Sum(l => l.LeaveTime.Hours) - Model.PartialSignin.Sum(a => a.ArrivedTime.Hours); }
                    <td><u>@(time)</u></td>
                    <td></td>
                </tr>
            </tbody>
        </table>



        @{ var monthOption = new List<SelectListItem>
           {
               new SelectListItem { Value = "1", Text = "一月" },
               new SelectListItem { Value = "2", Text = "二月" },
               new SelectListItem { Value = "3", Text = "三月" },
               new SelectListItem { Value = "4", Text = "四月" },
               new SelectListItem { Value = "5", Text = "五月" },
               new SelectListItem { Value = "6", Text = "六月" },
               new SelectListItem { Value = "7", Text = "七月" },
               new SelectListItem { Value = "8", Text = "八月" },
               new SelectListItem { Value = "9", Text = "九月" },
               new SelectListItem { Value = "10", Text = "十月" },
               new SelectListItem { Value = "11", Text = "十一月" },
               new SelectListItem { Value = "12", Text = "十二月" },
           };

            var yearOption = new List<SelectListItem>
           {
               new SelectListItem { Value = "2019", Text = "2019" },
               new SelectListItem { Value = "2020", Text = "2020" },
               new SelectListItem { Value = "2021", Text = "2021" },
               new SelectListItem { Value = "2022", Text = "2022" },
               new SelectListItem { Value = "2023", Text = "2023" },
               new SelectListItem { Value = "2024", Text = "2024" },
               new SelectListItem { Value = "2025", Text = "2025" },
               new SelectListItem { Value = "2026", Text = "2026" },
               new SelectListItem { Value = "2027", Text = "2027" },
               new SelectListItem { Value = "2028", Text = "2028" },
               new SelectListItem { Value = "2029", Text = "2029" },
               new SelectListItem { Value = "2030", Text = "2030" },
           };

            var nameOption = new List<SelectListItem>
           {
               new SelectListItem { Value = "Jeff Lu", Text = "Jeff" },
               new SelectListItem { Value = "Ted Tai", Text = "Ted" },
           };

            using (Html.BeginForm("AdminIndex", "Admin", FormMethod.Get))
            {
                @Html.DropDownList("year", new SelectList(yearOption, "Value", "Text"), "Select Year", new { @class = "form-control", style = "width:150px;" })
                @Html.DropDownList("month", new SelectList(monthOption, "Value", "Text"), "Select Month", new { @class = "form-control", style = "width:150px;" })
                @Html.DropDownList("internName", new SelectList(nameOption, "Value", "Text"), "Select Intern", new { @class = "form-control", style = "width:150px;" })
                <input class="form-control btn-success" type="submit" name="SaveButton" value="Submit" style="width:150px;" />
                <a href="ExportToExcel" id="exportLink">Export To Excel</a>
            }
        }
    </div>

Project2/Views/Admin/SigninDelete.cshtml
@model Project2.Azure_DB.Signin

@{
    ViewBag.Title = "SigninDelete";
}

<h2>SigninDelete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Signin</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.WorkDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.WorkDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ArrivedTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ArrivedTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LeaveTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LeaveTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CheckValue)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CheckValue)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

    <div class="form-actions no-color">
        <input type="submit" value="Delete" class="btn btn-default" /> |
            @{
                string internUrl = Request.Cookies["filterCookie"]["internUrl"];
                string yearUrl = Request.Cookies["filterCookie"]["yearUrl"];
                string monthUrl = Request.Cookies["filterCookie"]["monthUrl"];
            }
            @Html.ActionLink("Back to List", "AdminIndex", new { internName = internUrl, month = monthUrl, year = yearUrl })
    </div>
    }
</div>

Project2/Views/Admin/SigninEdit.cshtml
@model Project2.Azure_DB.Signin

@{
    ViewBag.Title = "SigninEdit";
}

<h2>SigninEdit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Signin</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.SigninId)

        <div class="form-group">
            @Html.LabelFor(model => model.WorkDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.WorkDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.WorkDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ArrivedTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ArrivedTime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ArrivedTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LeaveTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LeaveTime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LeaveTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CheckValue, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CheckValue, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CheckValue, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @{
        string internUrl = Request.Cookies["filterCookie"]["internUrl"];
        string yearUrl = Request.Cookies["filterCookie"]["yearUrl"];
        string monthUrl = Request.Cookies["filterCookie"]["monthUrl"];
    }
    @Html.ActionLink("Back to List", "AdminIndex", new { internName = internUrl, month = monthUrl, year = yearUrl })
</div>

Project2/Views/Admin/_WorkListPartial.cshtml
@model IEnumerable<Project2.Azure_DB.Task>


@{
    ViewBag.Title = "_WorkListPartial";
}


<link href="https://fonts.googleapis.com/css?family=Lato:400,700,700i,900&display=swap" rel="stylesheet">

<div class="container">
    <div class="list-inline">
        <div class="col-lg-10" style="padding-top:7px;">
            <h3>Work Record</h3>
        </div>
        <div class="col-lg-2">
            <h5 style="padding-top:40px;">@Html.ActionLink("To Sign-in Sheet", "Index", "Signin")</h5>
        </div>
    </div>
</div>
<div class="col-lg-2 navbar-fixed-bottom">
    <a href="@Url.Action("Create")">
        <img src="https://crsinternserviceimage.blob.core.windows.net/crsinternserviceimage/Group3.jpg" style="width:240px" />
    </a>
    <p>  </p>
</div>

<table class="table">
    <div class="page-holder w-100 d-flex flex-wrap">
        <div class="container-fluid px-xl-5">
            <section class="py-5">
                <div class="row">
                    <div class="col-lg-6 mb-4">
                        <div class="card">
                            <div class="card-header">
                            </div>
                            <div class="card-body">
                                <table class="table  table-hover card-text">
                                    <thead>
                                        <tr>
                                            <th>
                                                @Html.DisplayNameFor(model => model.TaskName)
                                            </th>
                                            <th>
                                                @Html.DisplayNameFor(model => model.Duration)
                                            </th>
                                            <th class="col-lg-3">
                                            </th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach (var item in Model)
                                        {
                                            <tr>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.TaskName)
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.Duration)
                                                </td>
                                                <td class="col-lg-2">
                                                    <a href="@Url.Action("WorklistEdit", new { id = item.TaskId })">
                                                        <img src="https://crsinternserviceimage.blob.core.windows.net/crsinternserviceimage/edit_btn.png" style="width:60px" />
                                                    </a>
                                                    <a href="@Url.Action("WorklistDelete", new { id = item.TaskId })">
                                                        <img src="https://crsinternserviceimage.blob.core.windows.net/crsinternserviceimage/delete_btn.png" style="width:80px" />
                                                    </a>
                                                </td>
                                            </tr>
                                        }
                                        <tr>
                                            <td></td>
                                            <td><u>@Model.Sum(b => b.Duration)</u></td>
                                            <td></td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </div>
    </div>
</table>

@section Scripts {
    @Scripts.Render("~/Content/FontStyle")
}